version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=${DEV}
    volumes:
      - ./:/app
    environment:
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "1"
